import os

TEMPLATE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "index.html")

TEMPLATE_LINES = [
    "[LT]!DOCTYPE html[GT]",
    "[LT]html lang='en'[GT]",
    "[LT]head[GT]",
    "  [LT]meta charset='UTF-8' /[GT]",
    "  [LT]meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' /[GT]",
    "  [LT]meta name='theme-color' content='#060913' /[GT]",
    "  [LT]meta name='mobile-web-app-capable' content='yes' /[GT]",
    "  [LT]meta name='apple-mobile-web-app-status-bar-style' content='black-translucent' /[GT]",
    "  [LT]link rel='manifest' href='/manifest.json' /[GT]",
    "  [LT]link rel='apple-touch-icon' href='https://cdn-icons-png.flaticon.com/512/2916/2916114.png' /[GT]",
    "  [LT]title[GT]Options Catalyst Desk[LT]/title[GT]",
    "  [LT]script src='https://s3.tradingview.com/tv.js'[GT][LT]/script[GT]",
    "  [LT]style[GT]",
    "    * { box-sizing: border-box; margin: 0; padding: 0; }",
    "    body { background: #060913; color: #e2e8f0; font-family: system-ui, sans-serif; padding: 24px; min-height: 100vh; }",
    "    header { display: flex; justify-content: space-between; margin-bottom: 20px; border-bottom: 1px solid #1e293b; padding-bottom: 16px; padding-right: 140px; }",
    "    h1 { font-size: 26px; color: #f8fafc; }",
    "    .btn-header-refresh { position: fixed; top: 20px; right: 24px; z-index: 999; display: flex; align-items: center; gap: 8px; background: #0f172a; color: #38bdf8; border: 1px solid #38bdf8; padding: 9px 18px; border-radius: 6px; font-weight: bold; cursor: pointer; box-shadow: 0 4px 16px rgba(0,0,0,0.7); }",
    "    .btn-header-refresh:hover { background: #1e293b; }",
    "    .icon-spin { display: inline-block; }",
    "    .spinning .icon-spin { animation: spin 0.8s linear infinite; }",
    "    @keyframes spin { 100% { transform: rotate(360deg); } }",
    "    .macro-bar { display: flex; flex-wrap: wrap; gap: 24px; background: #0f172a; border: 1px solid #1e293b; padding: 14px 20px; border-radius: 8px; font-size: 14px; margin-bottom: 16px; }",
    "    .macro-val { color: #38bdf8; font-weight: bold; margin-left: 4px; }",
    "    .badge-timestamp { background: #0b1329; color: #38bdf8; border: 1px solid #38bdf8; padding: 2px 10px; border-radius: 4px; font-size: 12px; font-weight: bold; margin-left: 10px; box-shadow: 0 0 8px rgba(56,189,248,0.25); }",
    "    .memory-banner { background: #090e1a; border: 1px solid #1e293b; border-left: 4px solid #8b5cf6; border-radius: 8px; padding: 14px 20px; margin-bottom: 24px; }",
    "    .memory-title { font-size: 11px; font-weight: bold; color: #a78bfa; text-transform: uppercase; margin-bottom: 6px; }",
    "    .memory-text { font-size: 13px; color: #cbd5e1; white-space: pre-line; line-height: 1.5; }",
    "    .section-title { font-size: 15px; font-weight: bold; color: #94a3b8; margin-bottom: 14px; text-transform: uppercase; }",
    "    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px; margin-bottom: 32px; }",
    "    .card { background: #0b1120; border: 1px solid #1e293b; border-radius: 10px; padding: 20px; cursor: pointer; position: relative; transition: all 0.15s ease; }",
    "    .card:hover { border-color: #38bdf8; transform: translateY(-3px); box-shadow: 0 4px 18px rgba(56,189,248,0.15); }",
    "    .trending-card { border-color: #e11d48; background: #0f0f1f; }",
    "    .trending-card:hover { border-color: #fb7185; }",
    "    .badge-rank { position: absolute; top: 16px; right: 16px; background: #e11d48; color: #fff; font-size: 11px; font-weight: bold; padding: 2px 8px; border-radius: 12px; }",
    "    .badge-signal { display: inline-block; padding: 4px 10px; font-size: 11px; font-weight: bold; border-radius: 4px; margin-bottom: 10px; text-transform: uppercase; }",
    "    .badge-signal.long { background: rgba(16,185,129,0.18); color: #10b981; border: 1px solid #10b981; }",
    "    .badge-signal.reversal { background: rgba(245,158,11,0.18); color: #f59e0b; border: 1px solid #f59e0b; }",
    "    .badge-signal.short { background: rgba(239,68,68,0.18); color: #ef4444; border: 1px solid #ef4444; }",
    "    .badge-signal.neutral { background: rgba(148,163,184,0.18); color: #94a3b8; border: 1px solid #94a3b8; }",
    "    .card h2 { font-size: 22px; color: #fff; margin-bottom: 8px; border-bottom: 1px solid #1e293b; padding-bottom: 4px; }",
    "    .card p { font-size: 13px; color: #94a3b8; margin: 6px 0; }",
    "    .val-price { color: #f8fafc; font-weight: bold; font-size: 15px; }",
    "    .val-regime, .val-trail { color: #38bdf8; font-weight: bold; }",
    "    .val-bias { color: #10b981; font-weight: bold; }",
    "    .modal-overlay { display: none; position: fixed; inset: 0; background: rgba(3,7,18,0.88); z-index: 1000; justify-content: center; align-items: center; padding: 20px; backdrop-filter: blur(8px); }",
    "    .modal-card { background: #090e1a; border: 1px solid #1e293b; border-radius: 14px; width: 100%; max-width: 900px; padding: 24px 28px; max-height: 92vh; overflow-y: auto; position: relative; }",
    "    .modal-close { position: absolute; top: 18px; right: 20px; background: none; border: none; color: #94a3b8; font-size: 26px; cursor: pointer; }",
    "    .desk-header { display: flex; justify-content: space-between; margin-bottom: 16px; }",
    "    .desk-title h3 { font-size: 30px; color: #fff; }",
    "    .desk-sub { color: #64748b; font-size: 13px; text-transform: uppercase; margin-top: 4px; }",
    "    .rating-badge { font-size: 26px; font-weight: bold; color: #10b981; text-align: right; }",
    "    .chart-container-box { width: 100%; height: 380px; border: 1px solid #1e293b; border-radius: 8px; background: #060913; margin-bottom: 20px; }",
    "    .chart-header-bar { display: flex; justify-content: space-between; padding: 6px 12px; background: #0b1329; border-bottom: 1px solid #1e293b; font-size: 11px; font-weight: bold; color: #94a3b8; text-transform: uppercase; }",
    "    .metric-grid-4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 16px; }",
    "    .metric-box { background: #0f172a; border: 1px solid #1e293b; padding: 10px 12px; border-radius: 8px; }",
    "    .metric-box label { font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: bold; }",
    "    .metric-box .val { font-size: 15px; color: #f8fafc; font-weight: bold; margin-top: 4px; }",
    "    .metric-box .sub { font-size: 11px; color: #94a3b8; margin-top: 2px; }",
    "    .scenario-container { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin: 16px 0; }",
    "    .scenario-box { border: 1px solid #1e293b; border-radius: 8px; padding: 14px; background: #0b1329; }",
    "    .scenario-box.bull { border-left: 4px solid #10b981; }",
    "    .scenario-box.bear { border-left: 4px solid #ef4444; }",
    "    .scenario-box h4 { font-size: 13px; font-weight: bold; margin-bottom: 10px; }",
    "    .scenario-row { display: flex; justify-content: space-between; font-size: 13px; color: #94a3b8; margin: 4px 0; }",
    "    .desk-view-box { background: #0d1527; border-left: 3px solid #38bdf8; padding: 12px 16px; font-size: 13px; color: #cbd5e1; margin-bottom: 16px; }",
    "    .bottom-layout { display: grid; grid-template-columns: 1.2fr 1fr; gap: 16px; }",
    "    .thesis-list { list-style: none; margin-top: 8px; }",
    "    .thesis-list li { font-size: 12px; color: #94a3b8; margin-bottom: 6px; padding-left: 16px; position: relative; }",
    "    .thesis-list li::before { content: '◆'; color: #38bdf8; position: absolute; left: 0; }",
    "    .level-pills { display: flex; gap: 8px; margin-top: 8px; }",
    "    .pill { background: #1e293b; color: #38bdf8; font-size: 11px; font-weight: bold; padding: 4px 8px; border-radius: 4px; }",
    "    ",
    "    /* MOBILE RESPONSIVENESS & BOTTOM SHEET MODAL */",
    "    @media (max-width: 768px) {",
    "      body { padding: 12px; }",
    "      header { padding-right: 0; flex-direction: column; align-items: flex-start; gap: 12px; border-bottom: none; margin-bottom: 10px; }",
    "      .btn-header-refresh { top: 12px; right: 12px; padding: 6px 12px; font-size: 12px; }",
    "      .macro-bar { flex-direction: column; align-items: flex-start; gap: 10px; padding: 12px; }",
    "      .badge-timestamp { margin-left: 0; margin-top: 6px; display: block; width: fit-content; }",
    "      .modal-overlay { align-items: flex-end; padding: 0; }",
    "      .modal-card { border-radius: 20px 20px 0 0; padding: 20px 16px; max-height: 90vh; animation: slideUp 0.3s ease-out forwards; }",
    "      @keyframes slideUp { from { transform: translateY(100%); } to { transform: translateY(0); } }",
    "      .modal-card::before { content: ''; display: block; width: 40px; height: 5px; background: #334155; border-radius: 3px; margin: 0 auto 16px auto; }",
    "      .modal-close { top: 16px; right: 16px; font-size: 28px; }",
    "      .desk-header { flex-direction: column; gap: 8px; }",
    "      .rating-badge { text-align: left; }",
    "      .chart-container-box { height: 280px; }",
    "      .metric-grid-4 { grid-template-columns: 1fr 1fr; }",
    "      .scenario-container { grid-template-columns: 1fr; }",
    "      .bottom-layout { grid-template-columns: 1fr; }",
    "    }",
    "  [LT]/style[GT]",
    "[LT]/head[GT]",
    "[LT]body[GT]",
    "  [LT]header[GT]",
    "    [LT]h1[GT]Options Catalyst Desk[LT]/h1[GT]",
    "  [LT]/header[GT]",
    "  [LT]button class='btn-header-refresh' type='button' onclick='refreshDesk()'[GT][LT]span class='icon-spin'[GT]🔄[LT]/span[GT] Refresh[LT]/button[GT]",
    "  [LT]div class='macro-bar'[GT]",
    "    [LT]div[GT]WTI Oil: [LT]span class='macro-val' id='macro-oil'[GT]{{ macro.get('WTI Crude', '$103.55 (+7.81%)') }}[LT]/span[GT][LT]/div[GT]",
    "    [LT]div[GT]10Y Yield: [LT]span class='macro-val' id='macro-yield'[GT]{{ macro.get('10Y Yield', '4.94%') }}[LT]/span[GT][LT]/div[GT]",
    "    [LT]div[GT]Tech/QQQ: [LT]span class='macro-val' id='macro-tech'[GT]{{ macro.get('Tech/QQQ', '$715.25 (-1.06%)') }}[LT]/span[GT][LT]/div[GT]",
    "    [LT]div[GT]🎯 1-Hr Accuracy: ",
    "      [LT]span class='macro-val' id='macro-accuracy' style='color:#10b981;'[GT]",
    "        {{ stats.win_rate if stats else 'N/A' }} ({{ stats.wins if stats else 0 }}W / {{ stats.losses if stats else 0 }}L)",
    "      [LT]/span[GT]",
    "      [LT]span class='badge-timestamp' id='macro-timestamp'[GT]--:--:-- CDT[LT]/span[GT]",
    "    [LT]/div[GT]",
    "  [LT]/div[GT]",
    "  [LT]div class='memory-banner'[GT]",
    "    [LT]div class='memory-title'[GT]🧠 Agentic Learning State & Retrospective Memory[LT]/div[GT]",
    "    [LT]div id='desk-memory-content' class='memory-text'[GT]{{ memory }}[LT]/div[GT]",
    "  [LT]/div[GT]",
    "  [LT]div class='section-title'[GT]TOP 3 X / FINTWIT TRENDING OPTIONS PLAYS[LT]/div[GT]",
    "  [LT]div class='grid' id='trendingGrid'[GT]",
    "    {% for card in trending_cards %}",
    "    [LT]div class='card trending-card' id='card-{{ card.symbol }}' onclick='openDossier(\"{{ card.symbol }}\")'[GT]",
    "      [LT]span class='badge-rank'[GT]#{{ card.social_rank }} X TRENDING[LT]/span[GT]",
    "      [LT]h2[GT]${{ card.symbol }}[LT]/h2[GT]",
    "      [LT]div class='badge-signal {% if \"LONG\" in card.recommendation %}long{% elif \"REVERSAL\" in card.recommendation %}reversal{% elif \"SHORT\" in card.recommendation %}short{% else %}neutral{% endif %}'[GT]",
    "        {{ card.recommendation }}",
    "      [LT]/div[GT]",
    "      [LT]p[GT]Price: [LT]span class='val-price'[GT]{{ card.price }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Wave Phase: [LT]span class='val-regime' style='color:#a78bfa;'[GT]{{ card.elliott_phase }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Fib Level: [LT]span class='val-regime'[GT]{{ card.fib_level }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Protection: [LT]span class='val-trail'[GT]{{ card.trailing_target }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Options Bias: [LT]span class='val-bias'[GT]{{ card.options_bias }}[LT]/span[GT][LT]/p[GT]",
    "    [LT]/div[GT]",
    "    {% endfor %}",
    "  [LT]/div[GT]",
    "  [LT]div class='section-title'[GT]CORE UNIVERSE (30-MINUTE INTRADAY ENGINE)[LT]/div[GT]",
    "  [LT]main class='grid' id='deskGrid'[GT]",
    "    {% for card in cards %}",
    "    [LT]div class='card' id='card-{{ card.symbol }}' onclick='openDossier(\"{{ card.symbol }}\")'[GT]",
    "      [LT]h2[GT]${{ card.symbol }}[LT]/h2[GT]",
    "      [LT]div class='badge-signal {% if \"LONG\" in card.recommendation %}long{% elif \"REVERSAL\" in card.recommendation %}reversal{% elif \"SHORT\" in card.recommendation %}short{% else %}neutral{% endif %}'[GT]",
    "        {{ card.recommendation }}",
    "      [LT]/div[GT]",
    "      [LT]p[GT]Price: [LT]span class='val-price'[GT]{{ card.price }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Wave Phase: [LT]span class='val-regime' style='color:#a78bfa;'[GT]{{ card.elliott_phase }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Fib Level: [LT]span class='val-regime'[GT]{{ card.fib_level }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Protection: [LT]span class='val-trail'[GT]{{ card.trailing_target }}[LT]/span[GT][LT]/p[GT]",
    "      [LT]p[GT]Options Bias: [LT]span class='val-bias'[GT]{{ card.options_bias }}[LT]/span[GT][LT]/p[GT]",
    "    [LT]/div[GT]",
    "    {% endfor %}",
    "  [LT]/main[GT]",
    "  [LT]div id='agentModal' class='modal-overlay' onclick='closeDossier(event)'[GT]",
    "    [LT]div class='modal-card' onclick='event.stopPropagation()'[GT]",
    "      [LT]button class='modal-close' onclick='document.getElementById(\"agentModal\").style.display=\"none\"'[GT]×[LT]/button[GT]",
    "      [LT]div class='desk-header'[GT]",
    "        [LT]div class='desk-title'[GT][LT]h3 id='dossier-sym'[GT]--[LT]/h3[GT][LT]div class='desk-sub' id='dossier-company'[GT]Loading profile...[LT]/div[GT][LT]/div[GT]",
    "        [LT]div[GT][LT]div class='desk-sub' style='text-align:right;'[GT]Suggested Action[LT]/div[GT][LT]div class='rating-badge' id='dossier-rating'[GT]LONG[LT]/div[GT][LT]/div[GT]",
    "      [LT]/div[GT]",
    "      [LT]div class='chart-header-bar'[GT][LT]span id='chart-sub-label'[GT]Intraday 5-Minute Chart (Extended Hours)[LT]/span[GT][LT]span style='color:#38bdf8;'[GT]Extended Feed[LT]/span[GT][LT]/div[GT]",
    "      [LT]div class='chart-container-box' id='tv-chart-box'[GT][LT]/div[GT]",
    "      [LT]div class='metric-grid-4'[GT]",
    "        [LT]div class='metric-box'[GT][LT]label[GT]Current Price[LT]/label[GT][LT]div class='val' id='dossier-price'[GT]--[LT]/div[GT][LT]div class='sub'[GT]Active Feed[LT]/div[GT][LT]/div[GT]",
    "        [LT]div class='metric-box'[GT][LT]label[GT]Price Target[LT]/label[GT][LT]div class='val' id='dossier-target'[GT]--[LT]/div[GT][LT]div class='sub' id='dossier-upside'[GT]Fib Extension[LT]/div[GT][LT]/div[GT]",
    "        [LT]div class='metric-box'[GT][LT]label[GT]Option Horizon[LT]/label[GT][LT]div class='val'[GT]Bi-Weekly[LT]/div[GT][LT]div class='sub'[GT]10–14 DTE[LT]/div[GT][LT]/div[GT]",
    "        [LT]div class='metric-box'[GT][LT]label[GT]Analysis Regime[LT]/label[GT][LT]div class='val' id='dossier-regime' style='color:#38bdf8;'[GT]Trending[LT]/div[GT][LT]div class='sub'[GT]30M Structure[LT]/div[GT][LT]/div[GT]",
    "      [LT]/div[GT]",
    "      [LT]div class='scenario-container'[GT]",
    "        [LT]div class='scenario-box bull'[GT]",
    "          [LT]h4 style='color:#10b981;'[GT]BULLISH PLAY [CALL OPTION][LT]/h4[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Entry Trigger:[LT]/span[GT] [LT]strong id='bull-trig'[GT]--[LT]/strong[GT][LT]/div[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Targets (Fib):[LT]/span[GT] [LT]strong id='bull-targets'[GT]--[LT]/strong[GT][LT]/div[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Invalidation:[LT]/span[GT] [LT]strong id='bull-inval'[GT]--[LT]/strong[GT][LT]/div[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Contract:[LT]/span[GT] [LT]strong style='color:#10b981;'[GT]0.60 Delta Call[LT]/strong[GT][LT]/div[GT]",
    "        [LT]/div[GT]",
    "        [LT]div class='scenario-box bear'[GT]",
    "          [LT]h4 style='color:#ef4444;'[GT]BEARISH PLAY [PUT OPTION][LT]/h4[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Breakdown:[LT]/span[GT] [LT]strong id='bear-trig'[GT]--[LT]/strong[GT][LT]/div[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Targets (Fib):[LT]/span[GT] [LT]strong id='bear-targets'[GT]--[LT]/strong[GT][LT]/div[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Invalidation:[LT]/span[GT] [LT]strong id='bear-inval'[GT]--[LT]/strong[GT][LT]/div[GT]",
    "          [LT]div class='scenario-row'[GT][LT]span[GT]Contract:[LT]/span[GT] [LT]strong style='color:#ef4444;'[GT]-0.60 Delta Put[LT]/strong[GT][LT]/div[GT]",
    "        [LT]/div[GT]",
    "      [LT]/div[GT]",
    "      [LT]div class='desk-view-box' id='dossier-deskview'[GT]Generating thesis...[LT]/div[GT]",
    "      [LT]div class='bottom-layout'[GT]",
    "        [LT]div[GT]",
    "          [LT]label style='font-size:11px; color:#64748b; font-weight:bold; text-transform:uppercase;'[GT]Execution Rules[LT]/label[GT]",
    "          [LT]ul class='thesis-list'[GT]",
    "            [LT]li[GT]Enter when 5-min candle closes past trigger.[LT]/li[GT]",
    "            [LT]li[GT]Scale 50% at Target 1, trail remainder on 30M EMA21.[LT]/li[GT]",
    "            [LT]li[GT]Hard invalidation on full candle close below stop.[LT]/li[GT]",
    "          [LT]/ul[GT]",
    "        [LT]/div[GT]",
    "        [LT]div[GT]",
    "          [LT]label style='font-size:11px; color:#64748b; font-weight:bold; text-transform:uppercase;'[GT]Liquidity Pivots[LT]/label[GT]",
    "          [LT]div class='level-pills'[GT]",
    "            [LT]span class='pill' id='lvl-s2'[GT]S2: --[LT]/span[GT]",
    "            [LT]span class='pill' id='lvl-s1'[GT]S1: --[LT]/span[GT]",
    "            [LT]span class='pill' id='lvl-pivot'[GT]P: --[LT]/span[GT]",
    "            [LT]span class='pill' id='lvl-r1'[GT]R1: --[LT]/span[GT]",
    "          [LT]/div[GT]",
    "          [LT]div style='margin-top:14px;'[GT]",
    "            [LT]label style='font-size:11px; color:#64748b; font-weight:bold; text-transform:uppercase;'[GT]News Catalyst[LT]/label[GT]",
    "            [LT]p id='dossier-news' style='font-size:12px; color:#cbd5e1; margin-top:4px;'[GT]Analyzing...[LT]/p[GT]",
    "          [LT]/div[GT]",
    "        [LT]/div[GT]",
    "      [LT]/div[GT]",
    "    [LT]/div[GT]",
    "  [LT]/div[GT]",
    "  [LT]script[GT]",
    "    if ('serviceWorker' in navigator) {",
    "      window.addEventListener('load', () => {",
    "        navigator.serviceWorker.register('/sw.js').catch(err => console.log('SW Registration failed', err));",
    "      });",
    "    }",
    "    function updateClock() {",
    "      let el = document.getElementById('macro-timestamp');",
    "      if(el) { el.innerText = new Date().toLocaleTimeString() + ' CDT'; }",
    "    }",
    "    updateClock(); setInterval(updateClock, 1000);",
    "    function renderTvChart(symbol) {",
    "      let box = document.getElementById('tv-chart-box');",
    "      box.innerHTML = '';",
    "      let div = document.createElement('div');",
    "      div.id = 'tv_container'; div.style.width = '100%'; div.style.height = '100%';",
    "      box.appendChild(div);",
    "      if(typeof TradingView !== 'undefined') {",
    "        new TradingView.widget({",
    "          'autosize': true,",
    "          'symbol': symbol,",
    "          'interval': '5',",
    "          'timezone': 'America/Chicago',",
    "          'theme': 'dark',",
    "          'style': '1',",
    "          'locale': 'en',",
    "          'toolbar_bg': '#0b1329',",
    "          'enable_publishing': false,",
    "          'hide_side_toolbar': true,",
    "          'allow_symbol_change': false,",
    "          'extended_hours': true,",
    "          'withdateranges': true,",
    "          'container_id': 'tv_container'",
    "        });",
    "      }",
    "    }",
    "    async function openDossier(symbol) {",
    "      document.getElementById('agentModal').style.display = 'flex';",
    "      document.getElementById('dossier-sym').innerText = '$' + symbol;",
    "      document.getElementById('chart-sub-label').innerText = symbol + ' - 5-Min Chart (Extended Hours Active)';",
    "      renderTvChart(symbol);",
    "      try {",
    "        let res = await fetch('/api/agent-desk/' + symbol + '?t=' + Date.now());",
    "        if(res.ok) {",
    "          let data = await res.json();",
    "          document.getElementById('dossier-company').innerText = data.company_name || symbol;",
    "          document.getElementById('dossier-rating').innerText = data.rating || 'ACTIVE';",
    "          if(data.bias_color) document.getElementById('dossier-rating').style.color = data.bias_color;",
    "          document.getElementById('dossier-price').innerText = data.premarket_price || '--';",
    "          document.getElementById('dossier-target').innerText = data.price_target || '--';",
    "          document.getElementById('dossier-upside').innerText = data.target_upside || '--';",
    "          document.getElementById('dossier-regime').innerText = data.regime || '--';",
    "          if(data.bull_leg) { document.getElementById('bull-trig').innerText = data.bull_leg.trigger; document.getElementById('bull-targets').innerText = data.bull_leg.targets; document.getElementById('bull-inval').innerText = data.bull_leg.invalidate; }",
    "          if(data.bear_leg) { document.getElementById('bear-trig').innerText = data.bear_leg.trigger; document.getElementById('bear-targets').innerText = data.bear_leg.targets; document.getElementById('bear-inval').innerText = data.bear_leg.invalidate; }",
    "          if(data.desk_view) document.getElementById('dossier-deskview').innerText = data.desk_view;",
    "          if(data.catalyst_headline) document.getElementById('dossier-news').innerText = data.catalyst_headline;",
    "          if(data.key_levels) { document.getElementById('lvl-s2').innerText = 'S2: ' + data.key_levels.s2; document.getElementById('lvl-s1').innerText = 'S1: ' + data.key_levels.s1; document.getElementById('lvl-pivot').innerText = 'P: ' + data.key_levels.pmh; document.getElementById('lvl-r1').innerText = 'R1: ' + data.key_levels.r1; }",
    "        }",
    "      } catch(e) { console.warn(e); }",
    "    }",
    "    function closeDossier(e) { if(e.target.id === 'agentModal') { document.getElementById('agentModal').style.display = 'none'; } }",
    "    async function refreshDesk() {",
    "      let btn = document.querySelector('.btn-header-refresh');",
    "      if(btn) { btn.classList.add('spinning'); }",
    "      try {",
    "        let res = await fetch('/api/refresh?t=' + Date.now());",
    "        let data = await res.json();",
    "        if(data.macro) {",
    "          if(document.getElementById('macro-oil')) document.getElementById('macro-oil').innerText = data.macro['WTI Crude'] || '--';",
    "          if(document.getElementById('macro-yield')) document.getElementById('macro-yield').innerText = data.macro['10Y Yield'] || '--';",
    "          if(document.getElementById('macro-tech')) document.getElementById('macro-tech').innerText = data.macro['Tech/QQQ'] || '--';",
    "        }",
    "        if(data.stats && document.getElementById('macro-accuracy')) document.getElementById('macro-accuracy').innerText = data.stats.win_rate + ' (' + data.stats.wins + 'W / ' + data.stats.losses + 'L)';",
    "        if(data.memory && document.getElementById('desk-memory-content')) document.getElementById('desk-memory-content').innerText = data.memory;",
    "        let updateCards = (list) => {",
    "          if(!list) return;",
    "          list.forEach(c => {",
    "            let el = document.getElementById('card-' + c.symbol);",
    "            if(!el) return;",
    "            let b = el.querySelector('.badge-signal');",
    "            if(b) {",
    "              b.innerText = c.recommendation;",
    "              let cls = 'neutral';",
    "              if(c.recommendation.includes('LONG')) cls = 'long';",
    "              else if(c.recommendation.includes('REVERSAL')) cls = 'reversal';",
    "              else if(c.recommendation.includes('SHORT')) cls = 'short';",
    "              b.className = 'badge-signal ' + cls;",
    "            }",
    "            let p = el.querySelector('.val-price'); if(p) p.innerText = c.price;",
    "            let regs = el.querySelectorAll('.val-regime'); if(regs.length >= 2) { regs[0].innerText = c.elliott_phase; regs[1].innerText = c.fib_level; }",
    "            let tr = el.querySelector('.val-trail'); if(tr) tr.innerText = c.trailing_target;",
    "            let bi = el.querySelector('.val-bias'); if(bi) bi.innerText = c.options_bias;",
    "          });",
    "        };",
    "        updateCards(data.cards); updateCards(data.trending_cards);",
    "      } catch(e) { console.error(e); }",
    "      finally { if(btn) setTimeout(() => btn.classList.remove('spinning'), 400); }",
    "    }",
    "    setInterval(refreshDesk, 10000);",
    "  [LT]/script[GT]",
    "[LT]/body[GT]",
    "[LT]/html[GT]"
]

html_content = "\n".join(TEMPLATE_LINES).replace("[LT]", "<").replace("[GT]", ">")

with open(TEMPLATE_PATH, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"[Success] Template compiled with Mobile Bottom-Sheet CSS and PWA Meta tags at: {TEMPLATE_PATH}")